package b.a;

import com.github.mikephil.charting.R;

public final class j {
    public static final int A = 3;
    public static final int A0 = 116;
    public static final int A1 = 12;
    public static final int A2 = 5;
    public static final int[] A3 = {16842752, 16842970, R.attr.paddingEnd, R.attr.paddingStart, R.attr.theme};
    public static final int B = 4;
    public static final int B0 = 117;
    public static final int B1 = 13;
    public static final int B2 = 6;
    public static final int B3 = 0;
    public static final int C = 5;
    public static final int C0 = 118;
    public static final int C1 = 14;
    public static final int C2 = 7;
    public static final int C3 = 4;
    public static final int[] D = {16842994, R.attr.buttonIconDimen, R.attr.buttonPanelSideLayout, R.attr.listItemLayout, R.attr.listLayout, R.attr.multiChoiceItemLayout, R.attr.showTitle, R.attr.singleChoiceItemLayout};
    public static final int D0 = 119;
    public static final int D1 = 15;
    public static final int D2 = 8;
    public static final int[] D3 = {16842964, R.attr.backgroundTint, R.attr.backgroundTintMode};
    public static final int E = 0;
    public static final int E0 = 120;
    public static final int E1 = 16;
    public static final int E2 = 9;
    public static final int E3 = 0;
    public static final int F = 1;
    public static final int F0 = 121;
    public static final int F1 = 17;
    public static final int F2 = 10;
    public static final int F3 = 1;
    public static final int G = 2;
    public static final int G0 = 122;
    public static final int G1 = 18;
    public static final int G2 = 11;
    public static final int G3 = 2;
    public static final int H = 3;
    public static final int H0 = 123;
    public static final int H1 = 19;
    public static final int H2 = 12;
    public static final int[] H3 = {16842960, 16842994, 16842995};
    public static final int I = 4;
    public static final int I0 = 124;
    public static final int I1 = 20;
    public static final int I2 = 13;
    public static final int I3 = 0;
    public static final int J = 5;
    public static final int[] J0 = {R.attr.allowStacking};
    public static final int J1 = 21;
    public static final int[] J2 = {16842901, 16842902, 16842903, 16842904, 16842906, 16842907, 16843105, 16843106, 16843107, 16843108, 16843692, 16844165, R.attr.fontFamily, R.attr.fontVariationSettings, R.attr.textAllCaps, R.attr.textLocale};
    public static final int J3 = 1;
    public static final int K = 6;
    public static final int K0 = 0;
    public static final int K1 = 22;
    public static final int K2 = 0;
    public static final int K3 = 2;
    public static final int L = 7;
    public static final int[] L0 = {16843015, R.attr.buttonCompat, R.attr.buttonTint, R.attr.buttonTintMode};
    public static final int[] L1 = {16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, R.attr.preserveIconSpacing, R.attr.subMenuArrow};
    public static final int L2 = 1;
    public static final int[] M = {16843033, R.attr.srcCompat, R.attr.tint, R.attr.tintMode};
    public static final int M0 = 0;
    public static final int M1 = 1;
    public static final int M2 = 2;
    public static final int N = 1;
    public static final int N0 = 1;
    public static final int N1 = 5;
    public static final int N2 = 3;
    public static final int O = 2;
    public static final int O0 = 2;
    public static final int O1 = 7;
    public static final int O2 = 4;
    public static final int P = 3;
    public static final int P0 = 3;
    public static final int P1 = 8;
    public static final int P2 = 5;
    public static final int[] Q = {16843074, R.attr.tickMark, R.attr.tickMarkTint, R.attr.tickMarkTintMode};
    public static final int[] Q0 = {16842927, 16842948, 16843046, 16843047, 16843048, R.attr.divider, R.attr.dividerPadding, R.attr.measureWithLargestChild, R.attr.showDividers};
    public static final int[] Q1 = {16843126, 16843465, R.attr.overlapAnchor};
    public static final int Q2 = 10;
    public static final int R = 0;
    public static final int R0 = 0;
    public static final int R1 = 0;
    public static final int R2 = 11;
    public static final int S = 1;
    public static final int S0 = 1;
    public static final int S1 = 2;
    public static final int S2 = 12;
    public static final int T = 2;
    public static final int T0 = 2;
    public static final int[] T1 = {R.attr.paddingBottomNoButtons, R.attr.paddingTopNoTitle};
    public static final int T2 = 13;
    public static final int U = 3;
    public static final int U0 = 3;
    public static final int U1 = 0;
    public static final int U2 = 14;
    public static final int[] V = {16842804, 16843117, 16843118, 16843119, 16843120, 16843666, 16843667};
    public static final int V0 = 4;
    public static final int V1 = 1;
    public static final int V2 = 15;
    public static final int W = 0;
    public static final int W0 = 5;
    public static final int[] W1 = {16842970, 16843039, 16843296, 16843364, R.attr.closeIcon, R.attr.commitIcon, R.attr.defaultQueryHint, R.attr.goIcon, R.attr.iconifiedByDefault, R.attr.layout, R.attr.queryBackground, R.attr.queryHint, R.attr.searchHintIcon, R.attr.searchIcon, R.attr.submitBackground, R.attr.suggestionRowLayout, R.attr.voiceIcon};
    public static final int[] W2 = {16842927, 16843072, R.attr.buttonGravity, R.attr.collapseContentDescription, R.attr.collapseIcon, R.attr.contentInsetEnd, R.attr.contentInsetEndWithActions, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.contentInsetStart, R.attr.contentInsetStartWithNavigation, R.attr.logo, R.attr.logoDescription, R.attr.maxButtonHeight, R.attr.menu, R.attr.navigationContentDescription, R.attr.navigationIcon, R.attr.popupTheme, R.attr.subtitle, R.attr.subtitleTextAppearance, R.attr.subtitleTextColor, R.attr.title, R.attr.titleMargin, R.attr.titleMarginBottom, R.attr.titleMarginEnd, R.attr.titleMarginStart, R.attr.titleMarginTop, R.attr.titleMargins, R.attr.titleTextAppearance, R.attr.titleTextColor};
    public static final int X = 1;
    public static final int X0 = 6;
    public static final int X1 = 0;
    public static final int X2 = 0;
    public static final int Y = 2;
    public static final int Y0 = 7;
    public static final int Y1 = 1;
    public static final int Y2 = 2;
    public static final int Z = 3;
    public static final int Z0 = 8;
    public static final int Z1 = 2;
    public static final int Z2 = 3;

    /* renamed from: a  reason: collision with root package name */
    public static final int[] f1998a = {R.attr.background, R.attr.backgroundSplit, R.attr.backgroundStacked, R.attr.contentInsetEnd, R.attr.contentInsetEndWithActions, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.contentInsetStart, R.attr.contentInsetStartWithNavigation, R.attr.customNavigationLayout, R.attr.displayOptions, R.attr.divider, R.attr.elevation, R.attr.height, R.attr.hideOnContentScroll, R.attr.homeAsUpIndicator, R.attr.homeLayout, R.attr.icon, R.attr.indeterminateProgressStyle, R.attr.itemPadding, R.attr.logo, R.attr.navigationMode, R.attr.popupTheme, R.attr.progressBarPadding, R.attr.progressBarStyle, R.attr.subtitle, R.attr.subtitleTextStyle, R.attr.title, R.attr.titleTextStyle};
    public static final int a0 = 4;
    public static final int[] a1 = {16842931, 16842996, 16842997, 16843137};
    public static final int a2 = 3;
    public static final int a3 = 4;

    /* renamed from: b  reason: collision with root package name */
    public static final int f1999b = 0;
    public static final int b0 = 5;
    public static final int b1 = 0;
    public static final int b2 = 4;
    public static final int b3 = 5;

    /* renamed from: c  reason: collision with root package name */
    public static final int f2000c = 1;
    public static final int c0 = 6;
    public static final int c1 = 3;
    public static final int c2 = 5;
    public static final int c3 = 6;

    /* renamed from: d  reason: collision with root package name */
    public static final int f2001d = 2;
    public static final int[] d0 = {16842804, R.attr.autoSizeMaxTextSize, R.attr.autoSizeMinTextSize, R.attr.autoSizePresetSizes, R.attr.autoSizeStepGranularity, R.attr.autoSizeTextType, R.attr.drawableBottomCompat, R.attr.drawableEndCompat, R.attr.drawableLeftCompat, R.attr.drawableRightCompat, R.attr.drawableStartCompat, R.attr.drawableTint, R.attr.drawableTintMode, R.attr.drawableTopCompat, R.attr.firstBaselineToTopHeight, R.attr.fontFamily, R.attr.fontVariationSettings, R.attr.lastBaselineToBottomHeight, R.attr.lineHeight, R.attr.textAllCaps, R.attr.textLocale};
    public static final int[] d1 = {16843436, 16843437};
    public static final int d2 = 6;
    public static final int d3 = 7;

    /* renamed from: e  reason: collision with root package name */
    public static final int f2002e = 3;
    public static final int e0 = 1;
    public static final int e1 = 0;
    public static final int e2 = 7;
    public static final int e3 = 8;

    /* renamed from: f  reason: collision with root package name */
    public static final int f2003f = 7;
    public static final int f0 = 2;
    public static final int f1 = 1;
    public static final int f2 = 8;
    public static final int f3 = 9;

    /* renamed from: g  reason: collision with root package name */
    public static final int f2004g = 9;
    public static final int g0 = 3;
    public static final int[] g1 = {16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
    public static final int g2 = 9;
    public static final int g3 = 10;

    /* renamed from: h  reason: collision with root package name */
    public static final int f2005h = 10;
    public static final int h0 = 4;
    public static final int h1 = 0;
    public static final int h2 = 10;
    public static final int h3 = 11;

    /* renamed from: i  reason: collision with root package name */
    public static final int f2006i = 12;
    public static final int i0 = 5;
    public static final int i1 = 1;
    public static final int i2 = 11;
    public static final int i3 = 12;

    /* renamed from: j  reason: collision with root package name */
    public static final int f2007j = 13;
    public static final int j0 = 6;
    public static final int j1 = 2;
    public static final int j2 = 12;
    public static final int j3 = 13;

    /* renamed from: k  reason: collision with root package name */
    public static final int f2008k = 14;
    public static final int k0 = 7;
    public static final int k1 = 3;
    public static final int k2 = 13;
    public static final int k3 = 14;
    public static final int l = 15;
    public static final int l0 = 8;
    public static final int l1 = 4;
    public static final int l2 = 14;
    public static final int l3 = 15;
    public static final int m = 17;
    public static final int m0 = 9;
    public static final int m1 = 5;
    public static final int m2 = 15;
    public static final int m3 = 16;
    public static final int n = 20;
    public static final int n0 = 10;
    public static final int[] n1 = {16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, R.attr.actionLayout, R.attr.actionProviderClass, R.attr.actionViewClass, R.attr.alphabeticModifiers, R.attr.contentDescription, R.attr.iconTint, R.attr.iconTintMode, R.attr.numericModifiers, R.attr.showAsAction, R.attr.tooltipText};
    public static final int n2 = 16;
    public static final int n3 = 17;
    public static final int o = 22;
    public static final int o0 = 11;
    public static final int o1 = 0;
    public static final int[] o2 = {16842930, 16843126, 16843131, 16843362, R.attr.popupTheme};
    public static final int o3 = 18;
    public static final int p = 25;
    public static final int p0 = 12;
    public static final int p1 = 1;
    public static final int p2 = 0;
    public static final int p3 = 19;
    public static final int q = 26;
    public static final int q0 = 13;
    public static final int q1 = 2;
    public static final int q2 = 1;
    public static final int q3 = 20;
    public static final int r = 27;
    public static final int r0 = 14;
    public static final int r1 = 3;
    public static final int r2 = 2;
    public static final int r3 = 21;
    public static final int s = 28;
    public static final int s0 = 17;
    public static final int s1 = 4;
    public static final int s2 = 3;
    public static final int s3 = 22;
    public static final int[] t = {16842931};
    public static final int t0 = 18;
    public static final int t1 = 5;
    public static final int t2 = 4;
    public static final int t3 = 23;
    public static final int u = 0;
    public static final int[] u0 = {16842839, 16842926, R.attr.actionBarDivider, R.attr.actionBarItemBackground, R.attr.actionBarPopupTheme, R.attr.actionBarSize, R.attr.actionBarSplitStyle, R.attr.actionBarStyle, R.attr.actionBarTabBarStyle, R.attr.actionBarTabStyle, R.attr.actionBarTabTextStyle, R.attr.actionBarTheme, R.attr.actionBarWidgetTheme, R.attr.actionButtonStyle, R.attr.actionDropDownStyle, R.attr.actionMenuTextAppearance, R.attr.actionMenuTextColor, R.attr.actionModeBackground, R.attr.actionModeCloseButtonStyle, R.attr.actionModeCloseDrawable, R.attr.actionModeCopyDrawable, R.attr.actionModeCutDrawable, R.attr.actionModeFindDrawable, R.attr.actionModePasteDrawable, R.attr.actionModePopupWindowStyle, R.attr.actionModeSelectAllDrawable, R.attr.actionModeShareDrawable, R.attr.actionModeSplitBackground, R.attr.actionModeStyle, R.attr.actionModeWebSearchDrawable, R.attr.actionOverflowButtonStyle, R.attr.actionOverflowMenuStyle, R.attr.activityChooserViewStyle, R.attr.alertDialogButtonGroupStyle, R.attr.alertDialogCenterButtons, R.attr.alertDialogStyle, R.attr.alertDialogTheme, R.attr.autoCompleteTextViewStyle, R.attr.borderlessButtonStyle, R.attr.buttonBarButtonStyle, R.attr.buttonBarNegativeButtonStyle, R.attr.buttonBarNeutralButtonStyle, R.attr.buttonBarPositiveButtonStyle, R.attr.buttonBarStyle, R.attr.buttonStyle, R.attr.buttonStyleSmall, R.attr.checkboxStyle, R.attr.checkedTextViewStyle, R.attr.colorAccent, R.attr.colorBackgroundFloating, R.attr.colorButtonNormal, R.attr.colorControlActivated, R.attr.colorControlHighlight, R.attr.colorControlNormal, R.attr.colorError, R.attr.colorPrimary, R.attr.colorPrimaryDark, R.attr.colorSwitchThumbNormal, R.attr.controlBackground, R.attr.dialogCornerRadius, R.attr.dialogPreferredPadding, R.attr.dialogTheme, R.attr.dividerHorizontal, R.attr.dividerVertical, R.attr.dropDownListViewStyle, R.attr.dropdownListPreferredItemHeight, R.attr.editTextBackground, R.attr.editTextColor, R.attr.editTextStyle, R.attr.homeAsUpIndicator, R.attr.imageButtonStyle, R.attr.listChoiceBackgroundIndicator, R.attr.listChoiceIndicatorMultipleAnimated, R.attr.listChoiceIndicatorSingleAnimated, R.attr.listDividerAlertDialog, R.attr.listMenuViewStyle, R.attr.listPopupWindowStyle, R.attr.listPreferredItemHeight, R.attr.listPreferredItemHeightLarge, R.attr.listPreferredItemHeightSmall, R.attr.listPreferredItemPaddingEnd, R.attr.listPreferredItemPaddingLeft, R.attr.listPreferredItemPaddingRight, R.attr.listPreferredItemPaddingStart, R.attr.panelBackground, R.attr.panelMenuListTheme, R.attr.panelMenuListWidth, R.attr.popupMenuStyle, R.attr.popupWindowStyle, R.attr.radioButtonStyle, R.attr.ratingBarStyle, R.attr.ratingBarStyleIndicator, R.attr.ratingBarStyleSmall, R.attr.searchViewStyle, R.attr.seekBarStyle, R.attr.selectableItemBackground, R.attr.selectableItemBackgroundBorderless, R.attr.spinnerDropDownItemStyle, R.attr.spinnerStyle, R.attr.switchStyle, R.attr.textAppearanceLargePopupMenu, R.attr.textAppearanceListItem, R.attr.textAppearanceListItemSecondary, R.attr.textAppearanceListItemSmall, R.attr.textAppearancePopupMenuHeader, R.attr.textAppearanceSearchResultSubtitle, R.attr.textAppearanceSearchResultTitle, R.attr.textAppearanceSmallPopupMenu, R.attr.textColorAlertDialogListItem, R.attr.textColorSearchUrl, R.attr.toolbarNavigationButtonStyle, R.attr.toolbarStyle, R.attr.tooltipForegroundColor, R.attr.tooltipFrameBackground, R.attr.viewInflaterClass, R.attr.windowActionBar, R.attr.windowActionBarOverlay, R.attr.windowActionModeOverlay, R.attr.windowFixedHeightMajor, R.attr.windowFixedHeightMinor, R.attr.windowFixedWidthMajor, R.attr.windowFixedWidthMinor, R.attr.windowMinWidthMajor, R.attr.windowMinWidthMinor, R.attr.windowNoTitle};
    public static final int u1 = 6;
    public static final int[] u2 = {16843044, 16843045, 16843074, R.attr.showText, R.attr.splitTrack, R.attr.switchMinWidth, R.attr.switchPadding, R.attr.switchTextAppearance, R.attr.thumbTextPadding, R.attr.thumbTint, R.attr.thumbTintMode, R.attr.track, R.attr.trackTint, R.attr.trackTintMode};
    public static final int u3 = 24;
    public static final int[] v = {16843071};
    public static final int v0 = 0;
    public static final int v1 = 7;
    public static final int v2 = 0;
    public static final int v3 = 25;
    public static final int w = 0;
    public static final int w0 = 1;
    public static final int w1 = 8;
    public static final int w2 = 1;
    public static final int w3 = 26;
    public static final int[] x = {R.attr.background, R.attr.backgroundSplit, R.attr.closeItemLayout, R.attr.height, R.attr.subtitleTextStyle, R.attr.titleTextStyle};
    public static final int x0 = 84;
    public static final int x1 = 9;
    public static final int x2 = 2;
    public static final int x3 = 27;
    public static final int y = 0;
    public static final int y0 = 114;
    public static final int y1 = 10;
    public static final int y2 = 3;
    public static final int y3 = 28;
    public static final int z = 2;
    public static final int z0 = 115;
    public static final int z1 = 11;
    public static final int z2 = 4;
    public static final int z3 = 29;
}
